package org.building.pmservice.service.wclient.SpotChkProj;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-06-11T14:16:56.921+08:00
 * Generated source version: 3.2.8
 *
 */
@WebService(targetNamespace = "http://www.anshanmining.com/pm/", name = "SI_SpotChkProj_in")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SISpotChkProjIn {

    @WebMethod(operationName = "SI_SpotChkProj", action = "http://sap.com/xi/WebService/soap1.1")
    @Oneway
    public void siSpotChkProj(
            @WebParam(partName = "MT_SPOTCHKPROJ", name = "MT_SPOTCHKPROJ", targetNamespace = "http://www.anshanmining.com/pm/")
                    DTSPOTCHECKPROJ mtSPOTCHKPROJ
    ) throws ZFAULTMSG_Exception;
}
