package org.building.pmservice.service.wclient.SpotChkProj;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-06-11T14:16:56.945+08:00
 * Generated source version: 3.2.8
 *
 */
@WebServiceClient(name = "SI_SpotChkProj_inService",
                  wsdlLocation = "file:/E:/设备/接口/fwsdl/SI_SpotChkProj_in.wsdl",
                  targetNamespace = "http://www.anshanmining.com/pm/")
public class SISpotChkProjInService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.anshanmining.com/pm/", "SI_SpotChkProj_inService");
    public final static QName SISpotChkProjInPort = new QName("http://www.anshanmining.com/pm/", "SI_SpotChkProj_inPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/设备/接口/fwsdl/SI_SpotChkProj_in.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SISpotChkProjInService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/E:/设备/接口/fwsdl/SI_SpotChkProj_in.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SISpotChkProjInService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SISpotChkProjInService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SISpotChkProjInService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SISpotChkProjInService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SISpotChkProjInService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SISpotChkProjInService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SISpotChkProjIn
     */
    @WebEndpoint(name = "SI_SpotChkProj_inPort")
    public SISpotChkProjIn getSISpotChkProjInPort() {
        return super.getPort(SISpotChkProjInPort, SISpotChkProjIn.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SISpotChkProjIn
     */
    @WebEndpoint(name = "SI_SpotChkProj_inPort")
    public SISpotChkProjIn getSISpotChkProjInPort(WebServiceFeature... features) {
        return super.getPort(SISpotChkProjInPort, SISpotChkProjIn.class, features);
    }

}
