
package org.building.pmservice.service.wclient.SpotChkProj;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-06-11T14:16:56.858+08:00
 * Generated source version: 3.2.8
 */

@WebFault(name = "ZFAULT_MSG", targetNamespace = "http://www.anshanmining.com/pm/")
public class ZFAULTMSG_Exception extends Exception {

    private org.building.pmservice.service.wclient.SpotChkProj.ZFAULTMSG zfaultMSG;

    public ZFAULTMSG_Exception() {
        super();
    }

    public ZFAULTMSG_Exception(String message) {
        super(message);
    }

    public ZFAULTMSG_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ZFAULTMSG_Exception(String message, org.building.pmservice.service.wclient.SpotChkProj.ZFAULTMSG zfaultMSG) {
        super(message);
        this.zfaultMSG = zfaultMSG;
    }

    public ZFAULTMSG_Exception(String message, org.building.pmservice.service.wclient.SpotChkProj.ZFAULTMSG zfaultMSG, Throwable cause) {
        super(message, cause);
        this.zfaultMSG = zfaultMSG;
    }

    public org.building.pmservice.service.wclient.SpotChkProj.ZFAULTMSG getFaultInfo() {
        return this.zfaultMSG;
    }
}
