package org.building.pmservice.service.wclient.JXWCJG;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-05-11T08:08:45.304+08:00
 * Generated source version: 3.2.8
 *
 */
@WebService(targetNamespace = "http://www.anshanmining.com/EAM_PM/", name = "SI_JXWCJG_Out_Syn")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIJXWCJGOutSyn {

    @WebMethod(operationName = "SI_JXWCJG", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_JXWCJGRet", targetNamespace = "http://www.anshanmining.com/EAM_PM/", partName = "MT_JXWCJGRet")
    public DTJXWCJGRet siJXWCJG(
            @WebParam(partName = "MT_JXWCJG", name = "MT_JXWCJG", targetNamespace = "http://www.anshanmining.com/EAM_PM/")
                    DTJXWCJG mtJXWCJG
    );
}
