package org.building.pmservice.service.wclient.JXWCJG;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-05-11T08:08:45.360+08:00
 * Generated source version: 3.2.8
 *
 */
@WebServiceClient(name = "SI_JXWCJG_Out_SynService",
                  wsdlLocation = "file:/E:/设备/接口/fwsdl/SI_JXWCJG_Out_Syn_PM0014.wsdl",
                  targetNamespace = "http://www.anshanmining.com/EAM_PM/")
public class SIJXWCJGOutSynService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.anshanmining.com/EAM_PM/", "SI_JXWCJG_Out_SynService");
    public final static QName SIJXWCJGOutSynPort = new QName("http://www.anshanmining.com/EAM_PM/", "SI_JXWCJG_Out_SynPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/设备/接口/fwsdl/SI_JXWCJG_Out_Syn_PM0014.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SIJXWCJGOutSynService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/E:/设备/接口/fwsdl/SI_JXWCJG_Out_Syn_PM0014.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SIJXWCJGOutSynService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SIJXWCJGOutSynService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIJXWCJGOutSynService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SIJXWCJGOutSynService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SIJXWCJGOutSynService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SIJXWCJGOutSynService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SIJXWCJGOutSyn
     */
    @WebEndpoint(name = "SI_JXWCJG_Out_SynPort")
    public SIJXWCJGOutSyn getSIJXWCJGOutSynPort() {
        return super.getPort(SIJXWCJGOutSynPort, SIJXWCJGOutSyn.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIJXWCJGOutSyn
     */
    @WebEndpoint(name = "SI_JXWCJG_Out_SynPort")
    public SIJXWCJGOutSyn getSIJXWCJGOutSynPort(WebServiceFeature... features) {
        return super.getPort(SIJXWCJGOutSynPort, SIJXWCJGOutSyn.class, features);
    }

}
