package org.building.pmservice.service.wclient.RYQX;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-05-14T15:17:45.713+08:00
 * Generated source version: 3.2.8
 *
 */
@WebService(targetNamespace = "http://www.anmining.com/tengxiaoxu/", name = "SI_RYQX_Out_Syn")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIRYQXOutSyn {

    @WebMethod(operationName = "SI_RYQX", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_RYQXRet", targetNamespace = "http://www.anmining.com/tengxiaoxu/", partName = "MT_RYQXRet")
    public DTRYQXRet siRYQX(
            @WebParam(partName = "MT_RYQX", name = "MT_RYQX", targetNamespace = "http://www.anmining.com/tengxiaoxu/")
                    DTRYQX mtRYQX
    );
}
