package org.building.pmservice.service.wclient.DJQXCLJG;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-05-13T14:04:08.041+08:00
 * Generated source version: 3.2.8
 *
 */
@WebService(targetNamespace = "http://www.anshanmining.com/EAM_PM/", name = "SI_DJQXCLJG_Out_Syn")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIDJQXCLJGOutSyn {

    @WebMethod(operationName = "SI_DJQXCLJG", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_DJQXCLJGRet", targetNamespace = "http://www.anshanmining.com/EAM_PM/", partName = "MT_DJQXCLJGRet")
    public DTDJQXCLJGRet siDJQXCLJG(
            @WebParam(partName = "MT_DJQXCLJG", name = "MT_DJQXCLJG", targetNamespace = "http://www.anshanmining.com/EAM_PM/")
                    DTDJQXCLJG mtDJQXCLJG
    );
}
