package org.building.pmservice.service.wclient.WWQX;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-05-10T19:42:56.345+08:00
 * Generated source version: 3.2.8
 *
 */
@WebService(targetNamespace = "http://www.anshanmining.com/EAM_PM/", name = "SI_WWQX_Out_Syn")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIWWQXOutSyn {

    @WebMethod(operationName = "SI_WWQX", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_WWQXRet", targetNamespace = "http://www.anshanmining.com/EAM_PM/", partName = "MT_WWQXRet")
    public DTWWQXRet siWWQX(
            @WebParam(partName = "MT_WWQX", name = "MT_WWQX", targetNamespace = "http://www.anshanmining.com/EAM_PM/")
                    DTWWQX mtWWQX
    );
}
