package org.building.pmservice.service.wclient.WWQX;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.8
 * 2019-05-10T19:42:56.393+08:00
 * Generated source version: 3.2.8
 *
 */
@WebServiceClient(name = "SI_WWQX_Out_SynService",
                  wsdlLocation = "file:/E:/设备/接口/fwsdl/SI_WWQX_Out_Syn_PM0011.wsdl",
                  targetNamespace = "http://www.anshanmining.com/EAM_PM/")
public class SIWWQXOutSynService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.anshanmining.com/EAM_PM/", "SI_WWQX_Out_SynService");
    public final static QName SIWWQXOutSynPort = new QName("http://www.anshanmining.com/EAM_PM/", "SI_WWQX_Out_SynPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/设备/接口/fwsdl/SI_WWQX_Out_Syn_PM0011.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SIWWQXOutSynService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/E:/设备/接口/fwsdl/SI_WWQX_Out_Syn_PM0011.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SIWWQXOutSynService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SIWWQXOutSynService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIWWQXOutSynService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SIWWQXOutSynService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SIWWQXOutSynService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SIWWQXOutSynService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SIWWQXOutSyn
     */
    @WebEndpoint(name = "SI_WWQX_Out_SynPort")
    public SIWWQXOutSyn getSIWWQXOutSynPort() {
        return super.getPort(SIWWQXOutSynPort, SIWWQXOutSyn.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIWWQXOutSyn
     */
    @WebEndpoint(name = "SI_WWQX_Out_SynPort")
    public SIWWQXOutSyn getSIWWQXOutSynPort(WebServiceFeature... features) {
        return super.getPort(SIWWQXOutSynPort, SIWWQXOutSyn.class, features);
    }

}
